version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
    - ./:/var/ratchet_ws/
    - ./_docker/conf.d/:/etc/nginx/conf.d
    ports:
    - "8875:80"
    container_name: ratchet_nginx
    networks:
      - ratchet
  php:
    build:
      context: .
      dockerfile: _docker/app/ws/Dockerfile
    volumes:
    - ./:/var/ratchet_ws/
    - ./_docker/app/ws/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: php
    networks:
      - ratchet
  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - ratchet
networks:
  ratchet:
    driver: bridge

volumes:
  db_data:
